controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_api_route:
    resource: 'routes/api.yaml'
    prefix: /api

app_front_route:
    resource: 'routes/front.yaml'